org.gradle.jvmargs=-Xmx2g -Dfile.encoding=UTF-8
org.gradle.parallel=true
kotlin.code.style=official
mavenCentralPublishing=true
mavenCentralAutomaticPublishing=true
signAllPublications=true

POM_NAME=WebSocketRecorder
POM_DESCRIPTION=A passive, listener-only WebSocket inspector for Kotlin, OkHttp, and Android.
POM_INCEPTION_YEAR=2026
POM_URL=https://github.com/rdevio/WebSocketRecorder
POM_LICENSE_NAME=The Apache License, Version 2.0
POM_LICENSE_URL=https://www.apache.org/licenses/LICENSE-2.0.txt
POM_LICENSE_DIST=repo
POM_SCM_URL=https://github.com/rdevio/WebSocketRecorder
POM_SCM_CONNECTION=scm:git:git://github.com/rdevio/WebSocketRecorder.git
POM_SCM_DEV_CONNECTION=scm:git:ssh://git@github.com/rdevio/WebSocketRecorder.git
POM_DEVELOPER_ID=rdevio
POM_DEVELOPER_NAME=Reza Sharifi
POM_DEVELOPER_EMAIL=rezasharify1993.rsmi@gmail.com
POM_DEVELOPER_URL=https://github.com/rdevio
signing.gnupg.keyName=5AC816797EE7D911
